#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python scripts/wait_for_postgres.py

python -m alembic upgrade head
uvicorn sni.main:app --reload --reload-include "**/*.md" --reload-include "**/*.json" --host 0.0.0.0
