set dotenv-filename := ".justenv"

env := env("ENV")
docker_compose_cmd := "docker compose -f docker-compose." + env + ".yml"

default:
  just --list

build:
  {{docker_compose_cmd}} build

up *args:
  {{docker_compose_cmd}} up {{args}} -d

watch *args:
  {{docker_compose_cmd}} watch {{args}}

stop:
  {{docker_compose_cmd}} stop

down:
  {{docker_compose_cmd}} down

logs *args: 
  {{docker_compose_cmd}} logs {{args}} -f

run *args:
  {{docker_compose_cmd}} run --rm fastapi {{args}}

exec *args:
  {{docker_compose_cmd}} exec fastapi {{args}}

bash:
  just exec bash

mm *args:
  just run alembic revision --autogenerate -m \"{{args}}\"

migrate:
  just run alembic upgrade head

upgrade *args:
  just run alembic upgrade {{args}}

downgrade *args:
  just run alembic downgrade {{args}}

import *args:
  just run python cli.py content initialize {{args}}

ruff *args:
  just run ruff {{args}} check .
  just run ruff format .
