set dotenv-filename := ".justenv"

env := env("ENV")
docker_compose_cmd := "docker compose -f docker-compose." + env + ".yml"

default:
  just --list

build:
  {{docker_compose_cmd}} build

up:
  {{docker_compose_cmd}} up -d

stop:
  {{docker_compose_cmd}} stop

down:
  {{docker_compose_cmd}} down

exec *args:
  {{docker_compose_cmd}} exec fastapi {{args}}

logs *args: 
  {{docker_compose_cmd}} logs {{args}} -f

mm *args:
  {{docker_compose_cmd}} exec fastapi alembic revision --autogenerate -m "{{args}}"

migrate:
  {{docker_compose_cmd}} exec fastapi alembic upgrade head

downgrade *args:
  {{docker_compose_cmd}} exec fastapi alembic downgrade {{args}}

ruff *args:
  {{docker_compose_cmd}} exec fastapi ruff {{args}} .
  {{docker_compose_cmd}} exec fastapi ruff format .
