---
---

<p>I have chosen the title of my lecture after a famous article by William H. Hutt, "The Yield from Money Held."<sup><a id="ref1" title="William H. Hutt, &quot;The Yield from Money Held,&quot; in: Freedom and Free Enterprise: Essays in Honor of Ludwig von Mises, ed. M. Sennholz, Chicago: Van Nostrand, 1956, pp. 196-216." href="#fn1">1</a></sup> Like Hutt, I want to attack the following notion: that money held in cash balances and deposit accounts is somehow "unproductive," "barren," or "sterile," offering a "yield of nil"; that only consumer goods and producer (investment) goods are productive of human welfare; that the only productive use of money lies in its "circulation," i.e., in its spending on consumer or producer goods; and that the holding, i.e., the not spending, of money diminishes future consumption and production.</p>

<p>This view is extremely popular within the economics profession and outside. Hutt offers many examples of its proponents. I will offer only two here. The first is John Maynard Keynes. One famous quote from his <em>General Theory</em> will suffice for my purpose: "An act of individual saving," by which Keynes means cash holding or "hoarding" instead of consumption or investment spending,</p>

<blockquote class="blockquote"><p>means — so to speak — a decision not to have dinner to-day. But it does <em>not</em> necessitate a decision to have dinner or buy a pair of boots a week hence or a year hence or to consume any specified thing at any specified date. Thus it depresses the business of preparing to-day's dinner without stimulating the business of making ready for some future act of consumption. It is not a substitution of future consumption-demand for present consumption-demand — it is a net diminution of such demand.<sup><a id="ref2" title="John Maynard Keynes, The General Theory of Employment, Interest, and Money, New York: Harcourt, Brace, and World, 1964, p. 210." href="#fn2">2</a></sup></p></blockquote>

<p>Here it is: the holding of money, i.e., the not spending of it on either consumer or investment goods, is unproductive, indeed detrimental. According to Keynes, the government or its central bank must create and then spend the money that "savers," i.e., the holders of cash balances, are unproductively holding back, so as to stimulate both consumption and investment. (Needless to say, this is precisely what governments and central banks are presently doing to supposedly rectify the current economic crisis.)</p>

<p>The second example is from closer to home, i.e., from the proponents of "free banking" such as Lawrence White, George Selgin, and Roger Garrison. According to them, an (unanticipated) increase in the demand for money "pushes the economy below its potential," (Garrison) and requires a compensating money-spending injection from the banking system.</p>

<p>Here it is again: an "excess demand for money" (Selgin and White) has no positive yield or is even detrimental; hence, help is needed. For the free bankers help is not supposed to come from the government and its central bank, but from a system of freely competing fractional-reserve banks. However, the idea involved is the same: the holding of (some, "excess") money is unproductive and requires a remedy.<sup><a id="ref3" title="Roger Garrison, &quot;Central Banking, Free Banking, and Financial Crises,&quot; Review of Austrian Economics 9, no.2, 1996, p. 117; George Selgin and Lawrence White, &quot;In Defense of Fiduciary Media,&quot; Review of Austrian Economics 9, no. 2, 1996, p. 100/01." href="#fn3">3</a></sup></p>

<p>I do not want to engage in a textual critique of Keynes or the "free bankers" here. I only mentioned them to further elucidate the idea that I want to attack, and to indicate how widespread — and consequential — its acceptance is within the economics profession, both inside and outside Keynesian circles. Unlike Hutt, who proceeds "critically" in his article, i.e., through a textual examination of various authors, and arrives at his own contrary view of the (positive) yield from money held in a rather indirect and circumstantial way, I want to proceed "apodictically": by way of a positive demonstration of money's unique productivity.<sup><a id="ref4" title="For a detailed critique of Keynes see Hans-Hermann Hoppe, &quot;Theory of Employment, Money, Interest, and the Capitalist Process: The Misesian Case Against Keynes&quot;; for a detailed critique of the free banking doctrine see idem, &quot;How is Fiat Money Possible?&quot; Review of Austrian Economics 7, no. 2, 1994 and idem, &quot;Against Fiduciary Media,&quot; Quarterly Journal of Austrian Economics 1, no.1, 1998." href="#fn4">4</a></sup></p>

<p>The first natural response to the thesis that money held in or added to cash balances is unproductive is to counter, Why, then, if money held in or added to cash balances is unproductive of human welfare, do people hold them or add to them? If cash holdings are indeed "good for nothing," no one would hold or add to them — and yet almost everyone does so all the time! And since all money is always held or hoarded by someone — when it "circulates," it only leaves one holding hand to be passed into another — money must be <em>continuously</em> "good for something" all the while it is being held (which is always).</p>

<p>To understand what this "good for something" of money is, it is best to ask, When, under what conditions, would there be <em>no</em> demand for cash holdings? Interestingly, wide agreement exists within the economics profession on the answer. It has been most lucidly stated by Ludwig von Mises. No money, and no demand for cash balances, would exist in "general equilibrium," or as Mises calls it, within the imaginary construction of an "evenly rotating economy." In this construction, all uncertainty is by assumption removed from human action. Everyone knows precisely the terms, times, and locations of every future action, and accordingly all exchanges can be prearranged and take the form of direct exchanges.</p>

<p>Writes Mises,</p>

<blockquote class="blockquote"><p>In a system without change in which there is no uncertainty whatever about the future, nobody needs to hold cash. Every individual knows precisely what amount of money he will need at any future date. He is therefore in a position to lend all the funds he receives in such a way that the loans fall due on the date he will need them.<sup><a id="ref5" title="Ludwig von Mises, Human Action, Chicago: Regnery, 1966, p. 249." href="#fn5">5</a></sup></p></blockquote>

<p>Based on this fundamental insight, we can state as a first provisional conclusion concerning the positive theory of money that money and cash balances would disappear with the disappearance of uncertainty (never) and, mutatis mutandis, that the investment in money balances must be conceived of as an investment in certainty or an investment in the reduction of subjectively felt uneasiness about uncertainty.</p>

<p>In reality, outside the imaginary construction of an evenly rotating economy, uncertainty exists. The terms, times, and locations of all future actions and exchanges cannot be predicted perfectly (with certitude). Action is by nature speculative and subject to error. Presently unpredictable surprises can occur. Whenever double coincidences of wants between pairs of prospective buyers and sellers are absent, for instance, i.e., when one does not want what the other has to sell or vice versa, any direct trade (exchange) becomes impossible.</p>

<p>Faced with this challenge of unpredictable contingencies, man can come to value goods on account of their degree of marketability (rather than their use-value for him as consumer or producer goods) and consider trading also whenever a good to be acquired is more marketable than that to be surrendered, such that its possession would facilitate the future acquisition of other directly or indirectly serviceable goods and services. That is, a demand for <em>media of exchange</em> can arise, i.e., a demand for goods valued on account of their marketability or resalability.</p>

<p>And since a more easily and widely resalable good is preferable to a less easily and widely resalable good as a medium of exchange, "there would be," as Mises writes,</p>

<blockquote class="blockquote"><p>an inevitable tendency for the less marketable of a series of goods used as media of exchange to be one by one rejected until at last only a single commodity remained, which was universally employed as a medium of exchange; in a word, money.<sup><a id="ref6" title="Ludwig von Mises, Theory of Money and Credit, Irvington, N.Y.: Foundation for Economic Education, 1971, pp. 32–33." href="#fn6">6</a></sup></p></blockquote>

<p>While this brief reconstruction of the origin of money is familiar, insufficient attention has been drawn to the fact that, as the most easily and widely salable good, money is at the same time the most universally <em>present</em> — <em>instantly</em> serviceable — good (which is why the interest rate, i.e., the discount rate of future goods against present goods, is expressed in terms of <em>money</em>) and, as such, the good uniquely suited to alleviate presently felt uneasiness about uncertainty.</p>

<p>Because money can be employed for the <em>instant satisfaction of the widest range of possible needs</em>, it provides its owner with the best humanly possible protection against uncertainty. In holding money, its owner gains in the satisfaction of being able to meet instantly, as they unpredictably arise, the widest range of future contingencies. The investment in cash balances is an investment contra the (subjectively felt) aversion to uncertainty. A larger cash balance brings more relief from uncertainty aversion.</p>

<p>The term <em>uncertainty aversion</em> is meant here in its technical sense, as opposed to risk aversion. The categorical distinction between <em>uncertainty</em> on the one hand and <em>risk</em> on the other was introduced into economics by Frank H. Knight and further elaborated on by Ludwig von Mises with his distinction between <em>case probability</em> and <em>class probability</em>.<sup><a id="ref7" title="Frank H. Knight, Risk, Uncertainty and Profit, Chicago: University of Chicago Press, 1971; Ludwig von Mises, Human Action, chap. VI." href="#fn7">7</a></sup></p>

<p>Risks (instances of class probability) are contingencies against which it is possible to take out insurance, because objective long-run probability distributions concerning all possible outcomes are known and predictable. We know nothing about an individual outcome, but we know everything about the whole class of events, and we are <em>certain</em> about the future.</p>

<p>Insofar as man faces a risky future, then, he does not need to hold cash. To satisfy his desire to be protected against risk, he can buy or produce insurance. The sum of money that he spends on insurance is an indication of the height of his aversion to risk. Insurance premiums are money <em>spent</em>, not held, and are as such invested in the physical production structure of producer and consumer goods. The payment of insurance reflects a man's subjectively felt <em>certainty</em> concerning (predictable) future contingencies (risks).</p>

<p>In distinct contrast, insofar as man faces <em>un</em>certainty he is, quite literally, <em>not</em> certain concerning future contingencies, i.e., as to what he might want or need and when. In order to be protected against unpredictable contingencies at unpredictable moments, he cannot invest in producer goods (as in the case of risk insurance); for such investments would reflect his <em>certainty</em> concerning particular future needs.</p>

<p>Only <em>present,</em> instantly serviceable goods can protect against unpredictable contingencies (uncertainty). Nor does a man want to invest in consumer goods for uncertainty protection. For an investment in consumer goods, too, is an expression of certainty concerning specific momentary or immediately impending wants. Only money, on account of its instant and unspecific wide-ranging salability, can protect him against uncertainty. Thus, just as insurance premiums are the price paid for protection against risk aversion, so cash holdings are the price paid for protection against uncertainty aversion.</p>

<p>To the extent that a man feels certain regarding his future needs, he will invest in consumer or producer goods. To invest in money balances is to invest neither in consumer goods nor producer goods. Unlike consumer and producer goods, which are used up in consumption or production, money is neither used up through its use as a medium of exchange nor transformed into another commodity. To invest in cash balances means, "I am uncertain about my present and future needs and believe that a balance of the most easily and widely saleable good on hand will best prepare me to meet my as-of-yet unknown needs at as-of-yet unknown times."</p>

<p>If a person then adds to his cash balance, he does so because he is confronted with a situation of (subjectively perceived) increased uncertainty regarding his future. The addition to his cash balance represents an investment in presently felt certainty vis-à-vis a future perceived as less certain. In order to add to his cash balance, a person must restrict his purchases or increase his sales of nonmoney goods (producer or consumer goods). In either case, the outcome is an immediate fall in certain nonmoney goods' prices. As the result of restricting his purchases of x, y, or z, the money price of x, y, or z will be lowered (as compared to what it would have been otherwise), and likewise, by increasing his sales of a, b, or c, their prices will fall.</p>

<p>The actor thus accomplishes exactly and immediately what he wants. He commands a larger (nominal and real) cash balance and is better prepared for an increasingly uncertain future. The marginal utility of the added cash is higher than (ranks above) the marginal utility of the nonmoney goods sold or unbought. He is better off with more cash on hand and less nonmoney goods, otherwise he would not have reallocated his assets in this way. There is more investment in the removal of perceived uncertainty, and there is less investment in needs, present or future, considered as certain.</p>

<p>The situation does not change if there is a <em>general</em> increase in the demand for money, i.e., if all or most people try to increase their cash holdings, in response to heightened uncertainty. With the total quantity of money given, the average size of cash holdings cannot increase, of course. Nor is the total quantity of producer and consumer goods that make up the physical production structure affected by a general increase in the demand for money. It remains unchanged.</p>

<p>In generally striving to increase the size of their cash holdings, however, the money prices of nonmoney goods will be bid down, and the purchasing power per unit money will correspondingly rise. Thus, the (increased) demand for and the (given) supply of money are equilibrated again, but at a higher purchasing power per unit money and lower prices of nonmoney goods. That is, even if nominal cash balances cannot rise as a result of a general increase in the demand for money, the <em>real</em> value of cash balances can; and it is this increase in the value of <em>real</em> cash balances that brings about precisely and immediately the effect desired: being better prepared for a future deemed as less certain.</p>

<p>No one cares about the nominal number of money units in his possession. Rather, people want to keep cash with a definite amount of purchasing power on hand. If the purchasing power per unit money increases as the result of an increased demand for cash holdings, each unit of money confronted with an array of generally lower nonmoney goods prices can do a better job in affording its owner protection against uncertainty.</p>

<p>This shall suffice as my attempt to provide a positive demonstration of the unique productivity of cash holdings as "yielders of certainty" in an uncertain world. Only a brief additional comment concerning the present, unprecedentedly severe economic crisis and the consequences that our theoretical considerations imply for its solution seems to be in order.</p>

<p>I shall say nothing here about the cause of the present crisis, except that I consider it another, spectacular vindication of the so-called Austrian — or "Mises-Hayek" — business-cycle theory. In any case, the crisis has led to heightened uncertainty. People want more certainty vis-à-vis a future considered far less certain than before. Accordingly, their demand for cash increases. With the quantity of money given, the higher demand for money can be satisfied only by bidding down nonmoney goods' prices. Consequently, as the overall "level" of prices falls, the purchasing power per unit money correspondingly rises. Each unit of money is productive now of more certainty, and the desired level of uncertainty protection is restored. The crisis is ended.</p>

<p>The solution to the crisis suggested instead by most economists and pundits and officially adopted by governments everywhere is entirely different. It is motivated by the here-criticized, fundamentally flawed doctrine that money held in or added to cash balances is money unproductively withheld from production and consumption. The additions to their cash holdings that people want to bring about are thus interpreted, wrongly, as a diminution of human welfare. Accordingly, huge efforts are now undertaken to increase the amount of spending.</p>

<p>But this stands at cross purpose to the general public's needs and desires: in order to be better protected against heightened perceived uncertainty, prices must fall and the purchasing power of money must rise. Yet with an influx of additional, newly created money, prices will be higher and the purchasing power per unit money will be lower than otherwise. Thus, as the result of the current monetary policy, the restoration of the desired level of uncertainty protection will be <em>delayed</em> and the crisis <em>prolonged</em>.</p>

<p><small>[Franz Cuhel Memorial Lecture, Prague, April 24, 2009]</small></p>

<hr>

<ol class="footnotes">
    <li id="fn1">William H. Hutt, "The Yield from Money Held," in: <em>Freedom and Free Enterprise: Essays in Honor of Ludwig von Mises</em>, ed. M. Sennholz, Chicago: Van Nostrand, 1956, pp. 196-216.&nbsp;<a href="#ref1">↩</a></li>

    <li id="fn2">John Maynard Keynes, <em>The General Theory of Employment, Interest, and Money</em>, New York: Harcourt, Brace, and World, 1964, p. 210.&nbsp;<a href="#ref2">↩</a></li>

    <li id="fn3">Roger Garrison, "Central Banking, Free Banking, and Financial Crises," Review of Austrian Economics 9, no.2, 1996, p. 117; George Selgin and Lawrence White, "In Defense of Fiduciary Media," <em>Review of Austrian Economics<em> 9, no. 2, 1996, p. 100/01.</em></em>&nbsp;<a href="#ref3">↩</a></li>

    <li id="fn4">For a detailed critique of Keynes see Hans-Hermann Hoppe, <a href="http://mises.org/daily/2492">"Theory of Employment, Money, Interest, and the Capitalist Process: The Misesian Case Against Keynes"</a>; for a detailed critique of the free banking doctrine see <em>idem</em>, <a href="/how-is-fiat-money-possible/">"How is Fiat Money Possible?"</a> <em>Review of Austrian Economics</em> 7, no. 2, 1994 and <em>idem</em>, "Against Fiduciary Media," <em>Quarterly Journal of Austrian Economics</em> 1, no.1, 1998.&nbsp;<a href="#ref4">↩</a></li>

    <li id="fn5">Ludwig von Mises, <a href="/literature/human-action/"><em>Human Action</em></a>, Chicago: Regnery, 1966, p. 249.&nbsp;<a href="#ref5">↩</a></li>

    <li id="fn6">Ludwig von Mises, <a href="/literature/theory-money-credit/"><em>Theory of Money and Credit</em></a>, Irvington, N.Y.: Foundation for Economic Education, 1971, pp. 32–33.&nbsp;<a href="#ref6">↩</a></li>

    <li id="fn7">Frank H. Knight, Risk, <em>Uncertainty and Profit</em>, Chicago: University of Chicago Press, 1971; Ludwig von Mises, <em>Human Action</em>, chap. VI.&nbsp;<a href="#ref7">↩</a></li>
</ul>
