"""empty message

Revision ID: 3f962a3ed355
Revises: 47056722357f
Create Date: 2014-05-03 12:54:04.388790

"""

# revision identifiers, used by Alembic.
revision = '3f962a3ed355'
down_revision = '47056722357f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('excerpt', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'excerpt')
    ### end Alembic commands ###
