"""Add quote cascade

Revision ID: 438caa40032e
Revises: a83ae97da366
Create Date: 2024-08-08 17:45:04.126467

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "438caa40032e"
down_revision: str | None = "a83ae97da366"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_quotes_email_id_emails", "quotes", type_="foreignkey")
    op.drop_constraint("fk_quotes_post_id_forum_posts", "quotes", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_quotes_post_id_forum_posts"),
        "quotes",
        "forum_posts",
        ["post_id"],
        ["satoshi_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_quotes_email_id_emails"),
        "quotes",
        "emails",
        ["email_id"],
        ["satoshi_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_quotes_email_id_emails"), "quotes", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_quotes_post_id_forum_posts"), "quotes", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_quotes_post_id_forum_posts",
        "quotes",
        "forum_posts",
        ["post_id"],
        ["satoshi_id"],
    )
    op.create_foreign_key(
        "fk_quotes_email_id_emails", "quotes", "emails", ["email_id"], ["satoshi_id"]
    )
    # ### end Alembic commands ###
