"""add slovak translations

Revision ID: 765fbf45c57c
Revises: 006948e4f251
Create Date: 2024-06-11 20:28:30.731386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '765fbf45c57c'
down_revision: Union[str, None] = '006948e4f251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'locales', ['ar', 'de', 'en', 'es', 'fa', 'fi', 'fr', 'he', 'it', 'ko', 'pt-br', 'ru', 'sk', 'tr', 'vi', 'zh-cn'],
                        [TableReference(table_schema='public', table_name='blog_series_translations', column_name='locale'), TableReference(table_schema='public', table_name='blog_post_translations', column_name='locale'), TableReference(table_schema='public', table_name='document_translations', column_name='locale')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'locales', ['ar', 'de', 'en', 'es', 'fa', 'fi', 'fr', 'he', 'it', 'ko', 'pt-br', 'ru', 'tr', 'vi', 'zh-cn'],
                        [TableReference(table_schema='public', table_name='blog_series_translations', column_name='locale'), TableReference(table_schema='public', table_name='blog_post_translations', column_name='locale'), TableReference(table_schema='public', table_name='document_translations', column_name='locale')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###
