"""Add disclaimer to emails and posts

Revision ID: 3260d1c44516
Revises: ae17263b6ead
Create Date: 2024-10-09 21:23:50.725511

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3260d1c44516"
down_revision: Union[str, None] = "ae17263b6ead"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("emails", sa.Column("disclaimer", sa.String(), nullable=True))
    op.add_column("forum_posts", sa.Column("disclaimer", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("forum_posts", "disclaimer")
    op.drop_column("emails", "disclaimer")
    # ### end Alembic commands ###
