"""Add volume to document_formats

Revision ID: d0e9a4846f4f
Revises: 4abcf6b66204
Create Date: 2025-03-31 00:26:10.581491

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0e9a4846f4f"
down_revision: Union[str, None] = "4abcf6b66204"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_formats", sa.Column("volume", sa.Integer(), nullable=True))
    op.drop_constraint(
        "uq_document_formats_format_type", "document_formats", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_document_formats_format_type"),
        "document_formats",
        ["format_type", "volume"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_document_formats_format_type"), "document_formats", type_="unique"
    )
    op.create_unique_constraint(
        "uq_document_formats_format_type", "document_formats", ["format_type"]
    )
    op.drop_column("document_formats", "volume")
    # ### end Alembic commands ###
