#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python scripts/wait_for_postgres.py

python -m alembic upgrade head
python cli.py content initialize
python cli.py cdn sync
uvicorn sni.main:app --host 0.0.0.0 --port 8000 --workers 4
