#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

/app/.venv/bin/python scripts/wait_for_postgres.py

/app/.venv/bin/python -m alembic upgrade head
/app/.venv/bin/python cli.py content initialize
/app/.venv/bin/python cli.py cdn sync
/app/.venv/bin/uvicorn sni.main:app --host 0.0.0.0 --port 8000 --workers 4
